#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

#This is specific to you module, so you need to change it accordingly.
host = data.get("host")
ADMIN_USERNAME = data.get("ADMIN_USERNAME", "listmonk")
ADMIN_PASSWORD = data.get("ADMIN_PASSWORD", "listmonk")
config = {
    "APP_HOST": "https://"+host,
    "ADMIN_USERNAME": ADMIN_USERNAME,
    "ADMIN_PASSWORD": ADMIN_PASSWORD,
}
agent.write_envfile("listmonk.env", config)

# just before starting systemd unit
#agent.dump_env()
