#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import os
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)
#  LISTMONK_app__address: 0.0.0.0:9000
# LISTMONK_db__user: *db-user
# LISTMONK_db__password: *db-password
# LISTMONK_db__database: *db-name
# LISTMONK_db__host: listmonk_db
# LISTMONK_db__port: 5432
# LISTMONK_db__ssl_mode: disable
# LISTMONK_db__max_open: 25
# LISTMONK_db__max_idle: 25
# LISTMONK_db__max_lifetime: 300s
# TZ: Etc/UTC
# LISTMONK_ADMIN_USER: ${LISTMONK_ADMIN_USER:-}           # If these (optional) are set during the first `docker compose up`, then the Super Admin user is automatically created.
# LISTMONK_ADMIN_PASSWORD: ${LISTMONK_ADMIN_PASSWORD:-}
# This is specific to you module, so you need to change it accordingly.
host = data.get("host")
ADMIN_USERNAME = data.get("ADMIN_USERNAME", "listmonk")
ADMIN_PASSWORD = data.get("ADMIN_PASSWORD", "listmonk")
config = {
    "LISTMONK_app__address": "https://" + host,
    "LISTMONK_ADMIN_USER": ADMIN_USERNAME,
    "LISTMONK_ADMIN_PASSWORD": ADMIN_PASSWORD,
}
if os.path.exists("database.env"):
    db = agent.read_envfile("database.env")
    config["LISTMONK_db__user"] = db.get("POSTGRES_USER")
    config["LISTMONK_db__password"] = db.get("POSTGRES_PASSWORD")
    config["LISTMONK_db__database"] = db.get("POSTGRES_DB")
    config["LISTMONK_db__host"] = "postgresql-app"
    config["LISTMONK_db__port"] = "5432"
    config["LISTMONK_db__ssl_mode"] = "disable"
    config["LISTMONK_db__max_open"] = 25
    config["LISTMONK_db__max_idle"] = 25
    config["LISTMONK_db__max_lifetime"] = "300s"

agent.write_envfile("listmonk.env", config)

# just before starting systemd unit
# agent.dump_env()
