#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# Read configuration
#

import os
import sys
import json
import agent

# Prepare return variable
config = {}
if os.path.exists("listmonk.env"):
    data = agent.read_envfile("listmonk.env")
    config["ADMIN_USERNAME"] = data.get("ADMIN_USERNAME")
    config["ADMIN_PASSWORD"] = data.get("ADMIN_PASSWORD")
else:
    config["ADMIN_USERNAME"] = ""
    config["ADMIN_PASSWORD"] = ""

# Read current configuration from the environment file
config["host"] = os.getenv("TRAEFIK_HOST", "")
config["http2https"] = os.getenv("TRAEFIK_HTTP2HTTPS") == "True"
config["lets_encrypt"] = os.getenv("TRAEFIK_LETS_ENCRYPT") == "True"

# Dump the configuration to stdout
json.dump(config, fp=sys.stdout)
